on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
      version:
        description: 'Application Version'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show parameters
        run: echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest mydockerhubusername/myapp:latest
          docker push mydockerhubusername/myapp:latest
